export const queryKeys = {
  session: ['session'] as const,
  profile: (userId: string) => ['profile', userId] as const,
  patient: (userId: string) => ['patient', userId] as const,
  physiotherapist: (userId: string) => ['physiotherapist', userId] as const,
  appointments: (filters?: Record<string, unknown>) => ['appointments', filters] as const,
  appointment: (id: string) => ['appointment', id] as const,
  physiotherapists: (modality?: string) => ['physiotherapists', modality] as const,
  availability: (physioId: string) => ['availability', physioId] as const,
  patientExercises: (patientId: string) => ['patient-exercises', patientId] as const,
  exerciseLibrary: ['exercise-library'] as const,
  clinicalRecords: (patientId: string) => ['clinical-records', patientId] as const,
  notifications: (userId: string) => ['notifications', userId] as const,
  adminStats: ['admin-stats'] as const,
  adminUsers: ['admin-users'] as const,
  physioPatients: (physioId: string) => ['physio-patients', physioId] as const,
  treatmentPlans: (patientId: string) => ['treatment-plans', patientId] as const,
  activeTreatmentPlan: (patientId: string) => ['active-treatment-plan', patientId] as const,
  treatmentGoals: (planId: string) => ['treatment-goals', planId] as const,
  checkIns: (patientId: string) => ['check-ins', patientId] as const,
  latestCheckIn: (patientId: string) => ['latest-check-in', patientId] as const,
  patientTimeline: (patientId: string) => ['patient-timeline', patientId] as const,
  clinicalProfile: (patientId: string) => ['clinical-profile', patientId] as const,
  consents: (patientId: string) => ['consents', patientId] as const,
  caregiverLinks: (patientId: string) => ['caregiver-links', patientId] as const,
  caregiverPatients: (caregiverProfileId: string) => ['caregiver-patients', caregiverProfileId] as const,
  payments: (patientId: string) => ['payments', patientId] as const,
  auditLogs: (filters?: Record<string, unknown>) => ['audit-logs', filters] as const,
  atRiskPatients: (physioId?: string) => ['at-risk-patients', physioId] as const,
  adherence: (patientId: string) => ['adherence', patientId] as const,
}
